services:
#    phrase.example:
#        class: PhraseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.random.phrase:
        class: PhraseBundle\Service\RandomPhrase
        arguments: ["@doctrine.orm.entity_manager"]